"""Configuration for the SmileyLlama -> geometry -> xTB pipeline.

Everything editable lives here. The stages (generate / xtb / plots) are pure CLI scripts
and never run inside a Jupyter kernel -- that is deliberate, see README.md.
"""
import os

# --- paths -----------------------------------------------------------------------
# Resolved from this file's location, so the checkout can live anywhere.
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Which SmileyLlama SMILES set to analyze. Override per-run without editing this file:
#   SYNTH_DATASET=1k_smiles_ro5 python -m synth.plots
#   1k_smiles_ro4 -> Rule-of-4 prompt (<=4 HBD/HBA, <=400 MW, <=4 logP), median MW 320.4
#   1k_smiles_ro5 -> Rule-of-5 prompt (<=5 HBD, <=10 HBA, <=500 MW, <=5 logP), median MW 395.4
# The two sets share only 11 molecules, so they are genuinely different populations.
#
# NOTE: these thresholds describe the PROMPT, not a filter. The post-hoc `is_druglike()`
# check in the generating notebook used the Ro5 thresholds for BOTH runs, so the Ro4
# constraint was never enforced post-hoc: 340/1000 ro4 molecules violate at least one
# prompted Ro4 property (71 over 400 Da, 128 over logP 4, 192 over 4 HBA, 2 over 4 HBD),
# measured with the same RDKit descriptors the notebook's own filter used
# (Descriptors.MolWt/MolLogP, Lipinski.NumHDonors/NumHAcceptors). The count is sensitive to
# that choice -- rdMolDescriptors.CalcNumHBA counts acceptors more liberally and gives
# 386/1000 -- so always say which definition you mean.
#
# This is a soft-constraint ADHERENCE result: the prompt shifts the distribution hard
# (median MW 395.4 -> 320.4, MW>400 drops 470 -> 71), which is how the paper frames it
# ("prompted with", "better overlap"). The sets are not filtered to the rule; do not
# describe them as guaranteed-compliant.
DATASET = os.environ.get('SYNTH_DATASET', '1k_smiles_ro4')
TAG = DATASET.split('_')[-1]          # 'ro4' | 'ro5' -- appears in the cache filenames

# Cached generations + the notebook's original xTB results (read-only inputs).
RESULTS_DIR = f'{REPO}/results/{DATASET}'

# Where this pipeline writes. Per-dataset, so ro4 and ro5 never overwrite each other.
CACHE_DIR = f'{REPO}/cache/{DATASET}'
FIG_DIR = f'{REPO}/figures/{DATASET}'

SMILES_PATH = f'{RESULTS_DIR}/ro5_smiles.json'  # notebook hardcodes this name for both runs

# --- methods ---------------------------------------------------------------------
# Colorblind-safe categorical pair, validated with synth/_validate_palette.py
# (CIEDE2000 >= 46 under normal/deuteranopia/protanopia/tritanopia; both >= 3:1 on white).
# Assign in fixed order; do NOT cycle or recolor when a series is filtered out.
#
# templated_z-matrix (template_fh) is intentionally NOT plotted here -- dropped per request.
# To bring it back, uncomment the block below AND re-run _validate_palette.py with the
# third color, since a 3rd series changes the pairwise CVD separation.
METHODS = [
    # {'name': 'templated_z-matrix',
    #  'path': 'models/template_fh/hybrid_8b_4e/outputs/merged',
    #  'format': 'template_fh', 'mode': 'free', 'color': '#1B9E77',
    #  'cache': f'{RESULTS_DIR}/template_fh_8b_4e_{TAG}_free_T1.json'},
    {'name': 'z-matrix',
     'path': 'models/8b_hybrid/4e_fh/outputs/merged',
     'format': 'ori_fh', 'mode': 'free', 'color': '#4682B4',
     'cache': f'{RESULTS_DIR}/ori_fh_8b_4e_{TAG}_free_T1.json'},
]

# RDKit ETKDGv3 is the reference baseline. Set to False to plot the model alone.
INCLUDE_RDKIT = True
RDKIT_NAME = 'rdkit'
RDKIT_COLOR = '#D95F02'
RDKIT_SEED = 42

# --- SMILES generation (synth.generate_smiles) -------------------------------------
# NOTE: the published SMILES were generated by the notebook, NOT by this code. These values
# are transcribed from smileyllama_synthesis_template_fh.py:120-185 so the regeneration path
# matches what was actually run. They cannot reproduce the published molecules -- see the
# seed discussion below and synth/README.md.
SMILEYLLAMA_PATH = 'THGLab/Llama-3.1-8B-SmileyLlama-1.1'   # revision unpinned, as published
N_SMILES = 1000
N_CONFORMERS_PER_SMILES = 10

SMILEY_SYSTEM = 'You love and excel at generating SMILES strings of drug-like molecules'

# The user prompt is what DEFINES each dataset -- it is the only thing that differed between
# the two published runs. Keyed by dataset, because a single SMILEY_USER silently generated
# Ro4 molecules no matter which SYNTH_DATASET you asked for.
SMILEY_USER_BY_DATASET = {
    '1k_smiles_ro4': ('Output a SMILES string for a drug like molecule with the following '
                      'properties: <= 4 H-bond donors, <= 4 H-bond acceptors, '
                      '<= 400 molecular weight, <= 4 logP'),
    '1k_smiles_ro5': ('Output a SMILES string for a drug like molecule with the following '
                      'properties: <= 5 H-bond donors, <= 10 H-bond acceptors, '
                      '<= 500 molecular weight, <= 5 logP'),
}
SMILEY_USER = SMILEY_USER_BY_DATASET.get(DATASET)

# Sampling. top_p is 1.0, NOT 0.95: the notebook hardcoded top_p=1.0 at the call site,
# overriding its own SMILEY_TOP_P constant. Transcribed as-run, deliberately.
SMILEY_TEMPERATURE = 1.0
SMILEY_TOP_P = 1.0
SMILEY_MAX_NEW_TOKENS = 8192
SMILEY_OVERSAMPLE = 2          # generate N_SMILES * this, then filter down to N_SMILES

# The published runs were UNSEEDED. None reproduces that behaviour (a different 1000 molecules
# every run); an int makes a rerun repeatable for a fixed vLLM/hardware/batch, but still cannot
# recover the published set. Either way, regeneration never reproduces the paper.
SMILEY_SEED = None

# The post-hoc druglike filter that was actually applied. Both published runs used the Ro5
# thresholds regardless of the prompt -- so the Ro4 set is prompt-conditioned, not filtered.
# This is a faithful transcription of the notebook's is_druglike(), not a fix.
SMILEY_FILTER = dict(max_mw=500, max_logp=5, max_hbd=5, max_hba=10)
SMILEY_EMBED_SEED = 0xf00d     # can_embed()'s ETKDGv3 seed

GEOM_TEMPERATURE = 1.0
GEOM_TOP_P = 0.95

# --- conformer selection ---------------------------------------------------------
# Which of the N_CONFORMERS_PER_SMILES generations represents each molecule.
#
# 'best_effort'     : 1. first atom-matched AND clash-free
#                     2. else the LAST atom-matched (they all clash)
#                     3. else the 10th structure (nothing matched -> reported as a mismatch)
#                     -> best-of-10, but an atom mismatch still means the model MISSED ALL 10.
# 'first'           : first generation per SMILES, as-is -> honest first-TRY success rate
# 'first_clashfree' : first clash-free, atom-matching conformer (silently drops total failures,
#                     which collapses the mismatch bar -- flattering, use with care)
# 'all_clashfree'   : every clash-free, atom-matching conformer
# 'all'             : every parsed conformer, no filtering
#
# The selected set is the DENOMINATOR for the invalid/mismatch overflow bars.
#
# *** 'best_effort' IS THE PUBLISHED SETTING (arXiv 2607.13350v1). ***
# It is the only value that reproduces the paper:
#     Fig 3 / Ro4 -> 84/1000  = 8.4%  atom mismatch ("84 of the 1000 Rule-of-Four molecules")
#            Ro5  -> 101/1000 = 10.1% atom mismatch ("atom mismatches are only 10%")
# Switching to 'first' silently yields 19.9% (ro4) instead -- a different, unpublished claim.
# The other strategies are kept for future work; anything other than 'best_effort' is NOT
# the paper. Every figure and CSV stamps the rule it was built with (see plots.provenance()).
#
# NOTE: selection happens in the xTB stage, so changing this requires re-running
#       `python -m synth.xtb_stage --method <name> --force`. It has NO effect on figures
#       plotted with `--source notebook` (that pickle has the notebook's choice baked in).
CONFORMER_SELECTION = 'best_effort'
PUBLISHED_SELECTION = 'best_effort'   # do not edit; used to warn on drift

# --- xTB -------------------------------------------------------------------------
XTB_MAX_ITER = 250
XTB_ACCURACY = 1.0
XTB_LEVEL = 'normal'
XTB_TIMEOUT = 600
# Each xtb call is pinned to 1 thread (OMP_NUM_THREADS=1) and the pool owns the parallelism,
# so this should track the node's core count. ~1000 molecules across 64 cores = a few minutes.
XTB_WORKERS = min(64, os.cpu_count() or 8)
CLASH_THRESHOLD = 0.7     # Angstrom

# The notebook's post-hoc `ok(s)` hardness filter (heavy<30, HBA<8, aromatic rings<4,
# FractionCSP3<0.6) has been REMOVED. It was never used for any published figure, and it
# silently narrowed the plotted population well below "drug-like". Do not reintroduce it
# without a `_filtered` suffix -- a filtered figure must never be mistaken for the full set.


def method_colors():
    c = {m['name']: m['color'] for m in METHODS}
    if INCLUDE_RDKIT:
        c[RDKIT_NAME] = RDKIT_COLOR
    return c


def plot_order():
    names = [m['name'] for m in METHODS]
    if INCLUDE_RDKIT:
        names.append(RDKIT_NAME)
    return names
