"""Stage 0: generate drug-like SMILES with SmileyLlama. GPU.

This is the stage that produces a dataset: prompt SmileyLlama under a Rule-of-N constraint,
keep the valid/unique/druglike/embeddable completions, stop at N_SMILES.

    python -m synth.generate_smiles --dry-run                    # show the prompt, no GPU
    python -m synth.generate_smiles                              # regenerate ro4 (~15 min)
    SYNTH_DATASET=1k_smiles_ro5 python -m synth.generate_smiles  # regenerate ro5

*** THIS CANNOT REPRODUCE THE PUBLISHED MOLECULES. ***

The published sets (arXiv:2607.13350v1) were generated by the notebook with no seed anywhere
in the sampling path, at T=1.0/top_p=1.0, against an unpinned model revision. Re-running here
draws a DIFFERENT, statistically equivalent 1000 molecules. So:

  - the published SMILES in results/<dataset>/ro5_smiles.json are the artifact of record and
    are never written by this module (it refuses, see _resolve_out);
  - regenerated sets land in results/regen/<dataset>/<tag>/ with a provenance sidecar and are
    a NEW sample, not the paper's.

Ported from the notebook's generation cell (smileyllama_synthesis_template_fh.py:120-185).
The quirks below are transcribed as-run, not fixed -- fixing them would silently change what
"the ro4 dataset" means:

  - top_p=1.0, though the notebook defined SMILEY_TOP_P=0.95 (hardcoded at the call site);
  - is_druglike() uses the Ro5 thresholds for BOTH prompts, so the Ro4 constraint was never
    enforced post-hoc -- 340/1000 published ro4 molecules violate a prompted Ro4 property
    (measured with the notebook's own Lipinski descriptors; see config.SMILEY_USER_BY_DATASET);
  - dedup happens BEFORE the druglike/embed checks, so a duplicate never gets a second chance;
  - the loop breaks at N_SMILES, so these are the FIRST 1000 survivors in generation order,
    not a random subset.

Run as its own process, never in a notebook kernel -- see README.md.
"""
import argparse
import json
import os

from . import config


def build_prompt(system_text, user_text):
    """The notebook's Alpaca prompt (smileyllama_synthesis_template_fh.py:114-117)."""
    return (f'### Instruction:\n{system_text}\n\n'
            f'### Input:\n{user_text}\n\n'
            f'### Response:\n')


def is_druglike(mol):
    """Faithful transcription of the notebook's is_druglike().

    Note these are the Ro5 thresholds and were applied to BOTH runs regardless of prompt.
    """
    from rdkit.Chem import Descriptors, Lipinski
    f = config.SMILEY_FILTER
    return (Descriptors.MolWt(mol) <= f['max_mw']
            and Descriptors.MolLogP(mol) <= f['max_logp']
            and Lipinski.NumHDonors(mol) <= f['max_hbd']
            and Lipinski.NumHAcceptors(mol) <= f['max_hba'])


def can_embed(mol):
    """Can RDKit produce a 3D conformer? (notebook's can_embed(), ETKDGv3 seed 0xf00d)"""
    from rdkit import Chem
    from rdkit.Chem import AllChem
    mh = Chem.AddHs(mol)
    p = AllChem.ETKDGv3()
    p.randomSeed = config.SMILEY_EMBED_SEED
    return AllChem.EmbedMolecule(mh, p) != -1


def filter_smiles(raw_smiles, n_wanted):
    """valid -> canonical -> dedup -> druglike -> embeddable, stopping at n_wanted.

    Order matters and is the notebook's: dedup precedes the chemistry checks, and the
    truncation is a break, so the result is the first n_wanted survivors in generation order.
    Returns (kept, stats).
    """
    from rdkit import Chem

    kept, seen = [], set()
    stats = {'raw': len(raw_smiles), 'unparseable': 0, 'duplicate': 0,
             'not_druglike': 0, 'not_embeddable': 0}
    for s in raw_smiles:
        mol = Chem.MolFromSmiles(s)
        if mol is None:
            stats['unparseable'] += 1
            continue
        canonical = Chem.MolToSmiles(mol)
        if canonical in seen:
            stats['duplicate'] += 1
            continue
        seen.add(canonical)
        if not is_druglike(mol):
            stats['not_druglike'] += 1
            continue
        if not can_embed(mol):
            stats['not_embeddable'] += 1
            continue
        kept.append(canonical)
        if len(kept) >= n_wanted:
            break
    stats['kept'] = len(kept)
    return kept, stats


def _resolve_out(explicit_out, force):
    """Where to write. Never the published artifact unless forced with eyes open."""
    published = config.SMILES_PATH
    if explicit_out is None:
        out = f'{config.REPO}/results/regen/{config.DATASET}/ro5_smiles.json'
    else:
        out = os.path.abspath(explicit_out)

    if os.path.abspath(out) == os.path.abspath(published) and not force:
        raise SystemExit(
            f'refusing to overwrite the published SMILES:\n  {published}\n'
            f'That file is the artifact of record for arXiv:2607.13350v1 and CANNOT be\n'
            f'regenerated (unseeded T=1.0 sampling) -- overwriting it destroys the only copy\n'
            f'of the data behind the published figures.\n'
            f'Regenerated sets go to results/regen/<dataset>/ by default. Pass --i-know-what-\n'
            f'i-am-doing only if you have a backup and truly mean it.')
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--n', type=int, default=config.N_SMILES, help='how many SMILES to keep')
    ap.add_argument('--oversample', type=int, default=config.SMILEY_OVERSAMPLE,
                    help='generate n*oversample candidates before filtering')
    ap.add_argument('--temperature', type=float, default=config.SMILEY_TEMPERATURE)
    ap.add_argument('--top-p', type=float, default=config.SMILEY_TOP_P)
    ap.add_argument('--seed', type=int, default=config.SMILEY_SEED,
                    help='sampling seed; default None = unseeded, as published')
    ap.add_argument('--max-new-tokens', type=int, default=config.SMILEY_MAX_NEW_TOKENS)
    ap.add_argument('--gpu-mem', type=float, default=0.90)
    ap.add_argument('--out', help='output JSON (default: results/regen/<dataset>/ro5_smiles.json)')
    ap.add_argument('--i-know-what-i-am-doing', action='store_true', dest='force',
                    help='allow --out to point at the published SMILES file')
    ap.add_argument('--dry-run', action='store_true', help='print the prompt and exit; no GPU')
    args = ap.parse_args()

    user_text = config.SMILEY_USER
    if user_text is None:
        raise SystemExit(
            f'no SmileyLlama prompt defined for dataset {config.DATASET!r}.\n'
            f'Known: {sorted(config.SMILEY_USER_BY_DATASET)}\n'
            f'The prompt is what defines the dataset -- add it to '
            f'config.SMILEY_USER_BY_DATASET before generating.')

    prompt = build_prompt(config.SMILEY_SYSTEM, user_text)
    out = _resolve_out(args.out, args.force)

    print(f'dataset:  {config.DATASET}')
    print(f'model:    {config.SMILEYLLAMA_PATH}  (revision unpinned)')
    print(f'sampling: T={args.temperature}, top_p={args.top_p}, seed={args.seed}, '
          f'n={args.n} kept of {args.n * args.oversample} candidates')
    print(f'out:      {out}')
    print(f'\n--- prompt ---\n{prompt}--- end prompt ---\n')

    if args.seed is None:
        print('seed=None: this run is NOT repeatable, matching how the published sets were '
              'made.\n           It will NOT reproduce the published molecules either way.\n')

    if args.dry_run:
        print('(dry run -- no model loaded)')
        return

    # Imported here so --help/--dry-run never touch CUDA.
    from geomllama.inference import InferenceEngine

    engine = InferenceEngine(model_path=config.SMILEYLLAMA_PATH,
                             gpu_memory_utilization=args.gpu_mem)
    results = engine.generate(
        prompts=[prompt] * (args.n * args.oversample),
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
        top_p=args.top_p,
        n=1,
        seed=args.seed,
    )

    # The completion is a SMILES on the first line; the notebook took exactly that.
    raw_smiles = [t.strip().split('\n')[0].strip() for _, texts in results for t in texts]

    kept, stats = filter_smiles(raw_smiles, args.n)

    print(f'\n=== filtering ({config.DATASET}) ===')
    for k in ('raw', 'unparseable', 'duplicate', 'not_druglike', 'not_embeddable', 'kept'):
        print(f'  {k:16s} {stats[k]}')
    if len(kept) < args.n:
        print(f'\n  WARNING: only {len(kept)}/{args.n} survived. Raise --oversample.')

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w') as f:
        json.dump(kept, f, indent=2)
    print(f'\nwrote {len(kept)} SMILES -> {out}')

    prov = {
        'note': 'REGENERATED SAMPLE -- not the published data of arXiv:2607.13350v1. '
                'The published molecules cannot be reproduced (unseeded T=1.0 sampling, '
                'unpinned model revision).',
        'dataset': config.DATASET,
        'model': config.SMILEYLLAMA_PATH,
        'model_revision': 'unpinned',
        'system_prompt': config.SMILEY_SYSTEM,
        'user_prompt': user_text,
        'full_prompt': prompt,
        'sampling': {'temperature': args.temperature, 'top_p': args.top_p,
                     'seed': args.seed, 'n': 1,
                     'max_new_tokens': args.max_new_tokens,
                     'n_prompts': args.n * args.oversample},
        'filter': dict(config.SMILEY_FILTER,
                       note='Ro5 thresholds; applied to BOTH prompts as published, so an '
                            'Ro4 set is prompt-conditioned, not filtered to the rule.'),
        'embed_seed': config.SMILEY_EMBED_SEED,
        'filter_stats': stats,
    }
    prov_path = os.path.join(os.path.dirname(out), 'provenance.json')
    with open(prov_path, 'w') as f:
        json.dump(prov, f, indent=2)
    print(f'wrote provenance -> {prov_path}')


if __name__ == '__main__':
    main()
